-- Migration 018: Realistic Jharkhand Civic Innovation Seed Data for SIH 2026 Presentation

-- 1. Seed Universities
INSERT INTO public.universities (name, short_name, district, type, specializations, active_teams, solved_challenges, incubation_cell, coordinator_name, coordinator_email, logo_url) VALUES
  ('Birla Institute of Technology (BIT) Mesra', 'BIT Mesra', 'Ranchi', 'Institute of National Eminence', ARRAY['Water Technology', 'IoT Sensors', 'Renewable Energy', 'Remote Sensing'], 14, 8, 'Technology Business Incubator (TBI) & DST NIDHI Cell', 'Prof. Amit Verma', 'dean.rnd@bitmesra.ac.in', 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=150&q=80'),
  ('National Institute of Technology (NIT) Jamshedpur', 'NIT Jamshedpur', 'East Singhbhum (Jamshedpur)', 'Institute of National Importance', ARRAY['Metallurgy', 'Rural Automation', 'Low-Cost Cold Storage', 'AI Diagnostics'], 12, 6, 'Center for Innovation, Incubation & Entrepreneurship', 'Dr. Sneha Srivastava', 'incubation@nitjsr.ac.in', 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?auto=format&fit=crop&w=150&q=80'),
  ('Indian Institute of Technology (IIT ISM) Dhanbad', 'IIT ISM Dhanbad', 'Dhanbad', 'Institute of National Importance', ARRAY['Mine Reclamation', 'Clean Coal', 'Air Quality Monitoring', 'Geotechnical'], 18, 11, 'Center for Mining Technology & ACIC Innovation Hub', 'Prof. R. K. Bhattacharya', 'acic@iitism.ac.in', 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&w=150&q=80'),
  ('Ranchi University', 'Ranchi University', 'Ranchi', 'State Public University', ARRAY['Tribal Linguistics', 'Botanical Extract Formulation', 'Medicinal Plants', 'Rural Sociology'], 8, 3, 'Tribal & Rural Entrepreneurship Development Cell', 'Dr. Meenakshi Munda', 'rnd@ranchiuniversity.ac.in', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=150&q=80'),
  ('Kolhan University', 'Kolhan University', 'West Singhbhum', 'State Public University', ARRAY['Indigenous Food Processing', 'Tasar Silk Weaving Machinery', 'Forest Produce'], 6, 2, 'Kolhan Innovation & Skill Hub', 'Prof. Arvind Murmu', 'innovation@kolhan.ac.in', 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=150&q=80')
ON CONFLICT (name) DO NOTHING;

-- 2. Seed Industry CSR Partners
INSERT INTO public.industry_partners (name, sector, district, csr_focus, funded_projects_count, grant_budget, contact_person, contact_email, logo_url) VALUES
  ('Tata Steel Foundation', 'Steel & Advanced Manufacturing', 'East Singhbhum (Jamshedpur)', ARRAY['Safe Drinking Water', 'Tribal STEM Education', 'Maternal Healthcare', 'Skill Training'], 24, '₹4.5 Crore', 'Dr. Vivek Sengupta', 'csr@tatasteel.com', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80'),
  ('Steel Authority of India Limited (SAIL Bokaro)', 'Public Sector Heavy Industry', 'Bokaro', ARRAY['Industrial Waste Upcycling', 'Panchayat Health Kiosks', 'Afforestation'], 16, '₹2.8 Crore', 'K. S. Ramanathan', 'csr.bokaro@sail.in', 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=150&q=80'),
  ('Central Coalfields Limited (CCL)', 'Mining & Mineral Extraction', 'Ranchi', ARRAY['Mine Overburden Remediation', 'Solar Rural Microgrids', 'Youth Technical Skilling'], 19, '₹3.2 Crore', 'Alok Kumar Shahi', 'csr@centralcoalfields.in', 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=150&q=80'),
  ('Jindal Steel & Power Limited (JSPL)', 'Energy & Steel', 'Ramgarh', ARRAY['Clean Energy', 'Women Micro-Enterprise Incubators', 'Agritech Supply Chains'], 11, '₹1.9 Crore', 'Pooja Agarwal', 'csr.patratu@jindalsteel.com', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80'),
  ('Tata Motors Jamshedpur', 'Automotive & Commercial Vehicles', 'East Singhbhum (Jamshedpur)', ARRAY['Electric Mobility', 'Technical Apprenticeship', 'Rural Road Safety'], 14, '₹2.4 Crore', 'Sunil Deshmukh', 'community.relations@tatamotors.com', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80')
ON CONFLICT (name) DO NOTHING;
